### ISSUE TITLE
Call for icons

### ISSUE THREAD

**Issue by floscher** [floscher/josm-mapillary-plugin#11]
I think it would be great, if we could have new icons. The current ones are based around the Mapillary logo with a small symbol indicating the functionality.

Perhaps the other way around would be better, a big symbol for the functionality and a small Mapillary logo or some other indication that the icon belongs to the Mapillary plugin (something like using the Mapillary-green as highlight-color or background-color).

The thing is, I'm not overly talented in icon design. So, I'd really appreciate if someone has suggestions for new icons or revised versions of the current icons.

New icons that we need:
* [x] Changeset dialog (currently the same one as for the history dialog is used)
* [x] Join mode (currently none)
* [x] Select mode (currently none)

Already existent icons that could be redesigned:
* [x] Main dialog that displays the images ![image](https://raw.githubusercontent.com/floscher/josm-mapillary-plugin/2ca23489b783a1897bae836bdd1358f583ddd4a7/images/dialogs/mapillary.png)
* [x] Filter dialog ![filter](https://raw.githubusercontent.com/floscher/josm-mapillary-plugin/2ca23489b783a1897bae836bdd1358f583ddd4a7/images/dialogs/mapillaryfilter.png)
* [x] History dialog ![history](https://raw.githubusercontent.com/floscher/josm-mapillary-plugin/2ca23489b783a1897bae836bdd1358f583ddd4a7/images/dialogs/mapillaryhistory.png)
* [ ] Traffic sign icon (currently unused) ![signs](https://raw.githubusercontent.com/floscher/josm-mapillary-plugin/2ca23489b783a1897bae836bdd1358f583ddd4a7/images/icon24sign.png)

The preferred size is 24×24px, because they'll be used for the JOSM sidebar, but SVGs would be even better, in case we'd need different sizes in the future.

cc @mapillary: Does someone of you have ideas? Maybe you already have symbols for certain actions/functionality like changesets, joining sequences or selecting images that we could reuse. That would make them also more recognizable between the website and the plugin.

**Comment by floscher** [comment]
Here is my take on redesigned icons: What if we simply take [material icons](https://design.google.com/icons/) in white on a background in mapillary-green? These icons are very simplistic and easily recognizable even in small sizes. Also all the mapillary-icons would still be quite uniform and distinguishable from all other icons in JOSM without using the logo over and over again.

It would look something like this:
![JOSM-screenshot](https://cloud.githubusercontent.com/assets/3904348/16716173/8593f9e6-46f5-11e6-8997-b9613b2db300.png)

* ![image dialog](https://cdn.rawgit.com/floscher/josm-mapillary-plugin/344c6efeca7b5f765812379c9e867a6969f5bd80/images/dialogs/mapillary.svg) for the main dialog displaying the images
* ![filter dialog](https://cdn.rawgit.com/floscher/josm-mapillary-plugin/344c6efeca7b5f765812379c9e867a6969f5bd80/images/dialogs/mapillaryfilter.svg) for the filter dialog
* ![history dialog](https://cdn.rawgit.com/floscher/josm-mapillary-plugin/344c6efeca7b5f765812379c9e867a6969f5bd80/images/dialogs/mapillaryhistory.svg) for the history dialog
* ![upload dialog](https://cdn.rawgit.com/floscher/josm-mapillary-plugin/344c6efeca7b5f765812379c9e867a6969f5bd80/images/dialogs/mapillaryupload.svg) for the changeset dialog (maybe rename it to "changeset upload dialog" or even only "upload dialog" because it is about *uploading* changes?)
* ![select mode](https://cdn.rawgit.com/floscher/josm-mapillary-plugin/344c6efeca7b5f765812379c9e867a6969f5bd80/images/dialogs/selectmode.svg) for the select mode (because it's mainly for moving images around)
* ![join mode](https://cdn.rawgit.com/floscher/josm-mapillary-plugin/344c6efeca7b5f765812379c9e867a6969f5bd80/images/dialogs/joinmode.svg) for the join mode

**Comment by nokutu** [comment]
Pretty awesome. Much better than the current ones.

**Comment by PolyglotOpenstreetmap** [comment]
Indeed, that would be great!

Jo

**Comment by floscher** [comment]
Credit goes to Google :wink:. I just recoloured them.

Do you know, if the licenses on the icons would cause any problems in GPL software? They are under CC-BY 4.0, only the move-icon is under SIL Open Font License 1.1.

**Comment by floscher** [comment]
OK, the new icons are now in master starting with 986d36e9df51b4507c70dc30bc94182b812dafed. I excluded the traffic signs icons, because it is currently not used.

As far as I understand, the licenses should be no problem, since the icons are distributed in an "aggretate" form, meaning they are used by the software but the software does not rely on these specific ones, so the icons could simply be replaced by other ones without the need to adapt the software.
