### ISSUE TITLE
Enhancing traffic sign system

### ISSUE THREAD

**Issue by nokutu** [floscher/josm-mapillary-plugin#16]
I've been trying to improve the traffic sign system, filtering maybe. There was an [issue](https://josm.openstreetmap.de/ticket/12068) with the signs in different countries. In order to fix this, I'm using the mapping files in [traffico repository](https://github.com/mapillary/traffico/tree/master/mapillary-mappings) (although I had to had at least one more), so I could translate among all the packages versions, as there are many images that contain old sign names.

I still have to check a couple of things so I merge it later.

**Comment by nokutu** [comment]
Btw @floscher, @peterneubauer do you know where I could download the list of the signs contained in the traffic signs packages?

**Comment by peterneubauer** [comment]
@nokutu we are using the traffico signs, http://traffico.io/ does that work?

**Comment by nokutu** [comment]
Well, @floscher did a couple of classes for the traffico font, but he was not using the mapping files for older packages. I should probably improve those so in the future we can use the font properly.

Atm I'm using the signs for filtering, so I only need the name, but maybe later we'll use the picture.

**Comment by blackboxlogic** [comment]
I'm trying to filter the signs shows on the mapilliary JOSM plugin's Traffic Signs layer. I'd like to only see "one-way" signs. This issue is the only place I found any mention of filtering but it's "closed as completed" and there's no documentation or code change around it. Does the feature exist?
