### ISSUE TITLE
Mapillary layer opens every time JOSM is started

### ISSUE THREAD

**Issue by floscher** [floscher/josm-mapillary-plugin#20]
As pointed out by @srividyacb in https://github.com/floscher/josm-mapillary-plugin/issues/18#issuecomment-246100857 the mapillary layer is currently opened every time you start JOSM and add any layer (e.g. Bing, or OSM data layer).

The expected behaviour would be for the Mapillary layer to open only when you choose the layer in the background imagery menu or hit `Shift`+`,`.

I also noticed, that the Mapillary layer will appear *above* the Bing layer but *below* the OSM data layer.

![Screencast showcasing the issue. After JOSM is started, the Bing layer is added and the Mapillary layer appears on top of the Bing layer](https://cloud.githubusercontent.com/assets/3423533/18409370/03e0f086-7763-11e6-9197-883152ebee66.gif)

**Comment by floscher** [comment]
This was also reported as https://josm.openstreetmap.de/ticket/13461 .

**Comment by nokutu** [comment]
This is already fixed, you'll see it when the new version is published.

**Comment by floscher** [comment]
:+1: Great, thanks! I saw that, just wanted to confirm the fix was committed and works as expected, which it is/does. Good job.
